### ISSUE TITLE
[Doc Request]: How to keep specific atoms alive if there's no watchers until the `AtomRoot` destroyed.

### ISSUE THREAD

**Issue by strangeliu** [ra1028/swiftui-atomic-architecture#7]
### Checklist

- [X] Reviewed the README and documentation.
- [X] Confirmed that this is uncovered by existing docs or examples.
- [X] Checked existing issues & PRs to ensure not duplicated.

### Description

Currently if there's no view watch a atom, it will auto unassigned, and later when a view watch if again, it will reset to default value.
If i want keep the atom value, i need to find a way to cache it when it recreate, or maybe a `EmptyView` watch at it at any time.
I wanna know if there's a better way to approach.

### Motivation & Context

Maybe a new property to define the life circle behavior of a atom, auto unassigned or alive if the AtomRoot exist.

**Comment by ra1028** [comment]
Hi @strangeliu ✋🏼 

You can consider using `KeepAlive` protocol so that the atom can keep maintaining the state even when it is no longer watched. If the atom conforms `KeepAlive` it will not be unassigned from the cache.
It is described in the following places:

- README: https://github.com/ra1028/swiftui-atomic-architecture#keepalive
- Doc: https://ra1028.github.io/swiftui-atomic-architecture/documentation/atoms/keepalive

**Comment by strangeliu** [comment]
Thanks, i have read the docs several times but still miss it. 😅
